name: CI

on: push

jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Instalar uv
        run: pip install uv
      - name: Instalar dependências
        run: uv sync
      - name: Validar lock file
        run: uv lock --locked
  linting:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Instalar uv
        run: pip install uv
      - name: Instalar dependências
        run: uv sync
      - name: Ruff Check
        run: uvx ruff check .
      - name: Ruff Format
        run: uvx ruff format --check .
  testing:
    runs-on: ubuntu-latest
    needs: [lock_file]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Instalar uv
        run: pip install uv

      - name: Instalar dependências
        run: uv sync

      - name: Executar testes
        run: uv run pytest